# Generated by Django 5.0.2 on 2024-03-07 12:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_quiz_end_time_quiz_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
